name: Call Azure Read
on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: "The name of the resource group to list"
        required: true
        type: string
        default: "RG-Lab"

    
jobs:
  call-azure:
    permissions:
      id-token: write
    uses: ./.github/workflows/azure-oidc-read.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      resourceGroup: ${{ inputs.resourceGroup }}

  show-results:
    needs: call-azure
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Show results from called workflow
        env:
          RG_LOCATION: ${{ needs.call-azure.outputs.location }}
        run: |
          echo "Resource group location: $RG_LOCATION"

