name: Call Azure Read
on:
  workflow_dispatch:
    
jobs:
  call-azure:
    permissions:
      id-token: write
    uses: ./.github/workflows/azure-oidc-read.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
